version: "3.8"

services:
  go:
    build:
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8008
    depends_on:
      - postgres
    stdin_open: true
    tty: true


  postgres:
    image: "postgres:16-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    environment:
      - POSTGRES_DB=starling
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data: {}
