version: "3.8"

x-default-app:
  &default-app
    build:
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    stdin_open: true
    tty: true

services:
  go:
    <<: *default-app
    ports:
      - 8888:8888

  worker:
    <<: *default-app
    command: air worker
    # If you don't need it
    # profiles:
    #   - donotstart

  postgres:
    image: "postgres:16-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    environment:
      - POSTGRES_DB=starling
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data: {}
